# Generated by Django 3.0.7 on 2021-03-07 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('txn_id', models.AutoField(primary_key=True, serialize=False)),
                ('txn_type', models.CharField(choices=[('CR', 'Credit'), ('DB', 'Debit')], max_length=2)),
                ('amount', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contacts.Contact')),
            ],
        ),
    ]
