# Generated by Django 3.0.7 on 2021-03-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='created_at',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='txn_id',
            field=models.UUIDField(primary_key=True, serialize=False),
        ),
    ]
